import { useOverlay } from "./context.tsx";
import { useStore } from "./store.ts";

const korean = new Map<string, string>(
  Object.entries({
    "Pick elements": "요소 선택",
    Single: "하나 선택",
    Box: "영역 선택",
    Lasso: "올가미",
    Capture: "캡처",
    Record: "녹화",
    Screenshot: "스크린샷",
    "Crop screenshot": "스크린샷 자르기",
    "Recording area": "녹화 영역",
    Annotate: "그리기",
    Rectangle: "사각형",
    Circle: "원",
    Freehand: "자유롭게 그리기",
    Debug: "디버그",
    Console: "콘솔",
    Network: "네트워크",
    Performance: "성능",
    Perf: "성능",
    Composer: "모아 보내기",
    Settings: "설정",
    Minimize: "최소화",
    History: "기록",
    Language: "언어",
    "Exit annotator": "주석 도구 종료",
    Annotation: "주석",
    Close: "닫기",
    "Loading editor…": "편집기 불러오는 중…",
    Prompt: "요청",
    "Global comment": "전체 의견",
    "No saved marks. Pick or capture to add one.":
      "저장된 주석이 없습니다. 요소를 선택하거나 캡처해 추가하세요.",
    "Continue current mark": "현재 주석 계속 편집",
    "Selected elements": "선택한 요소",
    "Saved marks": "저장된 주석",
    "Copy as Markdown": "마크다운으로 복사",
    "Ctrl / ⌘ Enter sends": "Ctrl / ⌘ Enter로 보내기",
    Save: "저장",
    Send: "보내기",
    "Send all": "모두 보내기",
    Text: "텍스트",
    "Text formatting": "텍스트 서식",
    "Block type": "블록 종류",
    Paragraph: "문단",
    Heading: "제목",
    "Bullet list": "글머리 목록",
    "Numbered list": "번호 목록",
    Quote: "인용",
    "Code block": "코드 블록",
    Bold: "굵게",
    Italic: "기울임",
    Recording: "녹화 중",
    "Elapsed time": "경과 시간",
    Stop: "중지",
    "Saving…": "저장 중…",
    "Record again": "다시 녹화",
    "Start recording": "녹화 시작",
    Video: "동영상",
    "Choose area": "영역 선택",
    "Change area": "영역 변경",
    "Whole viewport": "화면 전체",
    Reset: "초기화",
    "Choose this tab to share…": "공유할 탭으로 현재 탭을 선택하세요…",
    "Ready to annotate": "주석 작성 가능",
    "Open editor": "편집기 열기",
    "Capturing screenshot…": "스크린샷 캡처 중…",
    "Capturing…": "캡처 중…",
    "Draw on the page": "페이지에 그리세요",
    "Drag on the page": "페이지에서 드래그하세요",
    Cancel: "취소",
    "No prompt": "요청 없음",
    Agent: "에이전트",
    You: "나",
    Reply: "답글",
    "Send reply": "답글 보내기",
    "Nothing sent from this tab yet.": "이 탭에서 보낸 주석이 없습니다.",
    pending: "대기",
    acknowledged: "확인됨",
    resolved: "해결됨",
    dismissed: "닫힘",
  }),
);

export function useText(): (value: string) => string {
  const { ui } = useOverlay();
  const language = useStore(ui, (state) => state.language);
  return (value) => (language === "ko" ? (korean.get(value) ?? value) : value);
}
