import { useOverlay } from "./context.tsx";
import { useStore } from "./store.ts";

const korean = new Map<string, string>(
  Object.entries({
    "Pick elements": "요소 선택",
    Select: "선택",
    "⇧ Multi-select": "⇧ 복수 선택",
    Box: "영역 선택",
    Lasso: "올가미",
    Capture: "캡처",
    Record: "녹화",
    Screenshot: "스크린샷",
    Annotate: "그리기",
    Rectangle: "사각형",
    Circle: "원",
    Freehand: "그리기",
    Debug: "디버그",
    Console: "콘솔",
    Network: "네트워크",
    Performance: "성능",
    Perf: "성능",
    Composer: "모아 보내기",
    Settings: "설정",
    History: "기록",
    Language: "언어",
    "Exit annotator": "주석 도구 종료",
    Annotation: "주석",
    Close: "닫기",
    "Loading editor…": "편집기 불러오는 중…",
    Prompt: "요청",
    Annotator: "주석 도구",
    "Global comment": "전체 의견",
    "Edit mark": "주석 편집",
    "Remove mark": "주석 삭제",
    "Remove element": "요소 삭제",
    Remove: "삭제",
    "Add a note for all marks (optional)": "모든 주석에 덧붙일 의견 (선택)",
    "Describe the change…": "무엇을 바꿀지 적어 주세요…",
    "Selected elements": "선택한 요소",
    "Copy as Markdown": "마크다운으로 복사",
    Save: "저장",
    Send: "보내기",
    Recording: "녹화 중",
    "Elapsed time": "경과 시간",
    Stop: "중지",
    "Saving…": "저장 중…",
    Video: "동영상",
    "Choose this tab to share…": "공유할 탭으로 현재 탭을 선택하세요…",
    "Ready to annotate": "주석 작성 가능",
    "Open editor": "편집기 열기",
    "Capturing…": "캡처 중…",
    "Draw on the page": "페이지에 그리세요",
    "Drag an area · Click or ↵ for full": "영역 드래그 · 클릭 또는 ↵ 전체",
    Crop: "자르기",
    Confirm: "확인",
    Full: "전체",
    Area: "영역",
    Dictate: "받아쓰기",
    "Drag on the page": "페이지에서 드래그하세요",
    Cancel: "취소",
    "No prompt": "요청 없음",
    Agent: "에이전트",
    You: "나",
    pending: "대기",
    acknowledged: "확인됨",
    resolved: "해결됨",
    dismissed: "닫힘",
    "Copied to clipboard": "클립보드에 복사됨",
    "Couldn't copy to clipboard": "클립보드에 복사하지 못함",
    "Connect an agent over MCP for live replies":
      "MCP로 에이전트를 연결하면 바로 응답받을 수 있어요",
    "Connect agent": "에이전트에 연결하기",
    "Don't show again": "다시 보지 않기",
    OK: "확인",
  }),
);

export function useText(): (value: string) => string {
  const { ui } = useOverlay();
  const language = useStore(ui, (state) => state.language);
  return (value) => (language === "ko" ? (korean.get(value) ?? value) : value);
}
